## Data Preprocessing

In [14]:
import pandas as pd
import os

In [31]:
BASE = os.path.dirname(os.path.abspath('../RAW_recipes.csv'))
file_path = os.path.join(BASE, 'raw_data', 'RAW_recipes.csv')

df=pd.read_csv(file_path)


df.head(3)

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13

In [32]:
new_df=df.drop(columns=['name','id','minutes','contributor_id','submitted','tags','n_steps','description'])
new_df.head(3)

,nutrition,steps,ingredients,n_ingredients
0,"[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]","['make a choice and proceed with recipe', 'dep...","['winter squash', 'mexican seasoning', 'mixed ...",7
1,"[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]","['preheat oven to 425 degrees f', 'press dough...","['prepared pizza crust', 'sausage patty', 'egg...",6
2,"[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]","['brown ground beef in large pot', 'add choppe...","['ground beef', 'yellow onions', 'diced tomato...",13

In [33]:
# Breaking down nutrition column into individual macros columns
import json

In [34]:
calories=[]
fats=[]
protein=[]
carbs=[]
for i in new_df['nutrition']:
    i=json.loads(i)  #converting string representation of a list to an actual list
    calories.append(i[0])
    fats.append(i[1])
    protein.append(i[4])
    carbs.append(i[6])

In [35]:
new_df['calories']=calories
new_df['fats']=fats
new_df['protein']=protein
new_df['carbs']=carbs
new_df=new_df.drop(columns='nutrition')
new_df

,steps,ingredients,n_ingredients,calories,fats,protein,carbs
0,"['make a choice and proceed with recipe', 'dep...","['winter squash', 'mexican seasoning', 'mixed ...",7,51.5,0.0,2.0,4.0
1,"['preheat oven to 425 degrees f', 'press dough...","['prepared pizza crust', 'sausage patty', 'egg...",6,173.4,18.0,22.0,1.0
2,"['brown ground beef in large pot', 'add choppe...","['ground beef', 'yellow onions', 'diced tomato...",13,269.8,22.0,39.0,5.0
3,['place potatoes in a large pot of lightly sal...,"['spreadable cheese with garlic and herbs', 'n...",11,368.1,17.0,14.0,20.0
4,['mix all ingredients& boil for 2 1 / 2 hours ...,"['tomato juice', 'apple cider vinegar', 'sugar...",8,352.9,1.0,3.0,28.0
...,...,...,...,...,...,...,...
231632,"['heat oil in a 4-quart dutch oven', 'add cele...","['celery', 'onion', 'green sweet pepper', 'gar...",22,415.2,26.0,44.0,15.0
231633,['mix all ingredients together thoroughly'],"['paprika', 'salt', 'garlic powder', 'onion po...",13,14.8,0.0,1.0,1.0
231634,"['in a bowl , combine the mashed yolks and may...","['hard-cooked eggs', 'mayonnaise', 'dijon must...",8,59.2,6.0,6.0,0.0
231635,['place melted butter in a large mixing bowl a...,"['butter', 'eagle brand condensed milk', 'ligh...",10,188.0,11.0,7.0,9.0
231636,"['whip sugar and shortening in a large bowl , ...","['granulated sugar', 'shortening', 'eggs', 'fl...",7,174.9,14.0,4.0,6.0

In [36]:
import ast

In [37]:
ingredients=[]
for j in new_df['ingredients']:
    j= ast.literal_eval(j)  #converting string representation of a list to an actual list
    ingredients.append(j)
new_df['ingredients']=ingredients

In [12]:
new_df['steps'][0]

"['make a choice and proceed with recipe', 'depending on size of squash , cut into half or fourths', 'remove seeds', 'for spicy squash , drizzle olive oil or melted butter over each cut squash piece', 'season with mexican seasoning mix ii', 'for sweet squash , drizzle melted honey , butter , grated piloncillo over each cut squash piece', 'season with sweet mexican spice mix', 'bake at 350 degrees , again depending on size , for 40 minutes up to an hour , until a fork can easily pierce the skin', 'be careful not to burn the squash especially if you opt to use sugar or butter', 'if you feel more comfortable , cover the squash with aluminum foil the first half hour , give or take , of baking', 'if desired , season with salt']"

In [40]:
new_df.to_csv('preprocessed.csv')