## Data Preprocessing

In [11]:
import pandas as pd
import os

# Recipe Data Preprocessing : Recipe data to recommend to the user

In [12]:
#Opening raw_recipes csv file in the raw data folder

BASE = os.path.dirname(os.path.abspath('../RAW_recipes.csv'))
file_path = os.path.join(BASE, 'raw_data', 'RAW_recipes.csv')

df=pd.read_csv(file_path)


df.head(3)

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13

In [13]:
new_df=df.drop(columns=['name','id','minutes','contributor_id','submitted','tags','n_steps','description'])
new_df.head(3)

,nutrition,steps,ingredients,n_ingredients
0,"[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]","['make a choice and proceed with recipe', 'dep...","['winter squash', 'mexican seasoning', 'mixed ...",7
1,"[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]","['preheat oven to 425 degrees f', 'press dough...","['prepared pizza crust', 'sausage patty', 'egg...",6
2,"[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]","['brown ground beef in large pot', 'add choppe...","['ground beef', 'yellow onions', 'diced tomato...",13

In [14]:
# Breaking down nutrition column into individual macros columns
import json

In [15]:
calories=[]
fats=[]
protein=[]
carbs=[]
for i in new_df['nutrition']:
    i=json.loads(i)  #converting string representation of a list to an actual list
    calories.append(i[0])
    fats.append(i[1])
    protein.append(i[4])
    carbs.append(i[6])

In [16]:
new_df['calories']=calories
new_df['fats']=fats
new_df['protein']=protein
new_df['carbs']=carbs
new_df=new_df.drop(columns=['nutrition','steps','n_ingredients'])
new_df

,ingredients,calories,fats,protein,carbs
0,"['winter squash', 'mexican seasoning', 'mixed ...",51.5,0.0,2.0,4.0
1,"['prepared pizza crust', 'sausage patty', 'egg...",173.4,18.0,22.0,1.0
2,"['ground beef', 'yellow onions', 'diced tomato...",269.8,22.0,39.0,5.0
3,"['spreadable cheese with garlic and herbs', 'n...",368.1,17.0,14.0,20.0
4,"['tomato juice', 'apple cider vinegar', 'sugar...",352.9,1.0,3.0,28.0
...,...,...,...,...,...
231632,"['celery', 'onion', 'green sweet pepper', 'gar...",415.2,26.0,44.0,15.0
231633,"['paprika', 'salt', 'garlic powder', 'onion po...",14.8,0.0,1.0,1.0
231634,"['hard-cooked eggs', 'mayonnaise', 'dijon must...",59.2,6.0,6.0,0.0
231635,"['butter', 'eagle brand condensed milk', 'ligh...",188.0,11.0,7.0,9.0
231636,"['granulated sugar', 'shortening', 'eggs', 'fl...",174.9,14.0,4.0,6.0

In [17]:
import ast

In [18]:
# Convert string representations of lists to actual lists using map() and ast.literal_eval()
new_df['ingredients'] = new_df['ingredients'].map(ast.literal_eval)

# Verify the updated data type
print(new_df['ingredients'].dtype)  # Output: object (if the dtype is still showing as object)

# Convert the column to a list data type
new_df['ingredients'] = new_df['ingredients'].map(list)

# Verify the updated data type
print(new_df['ingredients'].dtype)  # Output: object (if the dtype is still showing as object)

# ingredients=[]
# for j in new_df['ingredients']:
#     j= ast.literal_eval(j)  #converting string representation of a list to an actual list
#     ingredients.append(j)
# new_df['ingredients']=ingredients

object
object

In [19]:
ingredients_list = [i for i in new_df['ingredients'][0]]
print(ingredients_list)
type(ingredients_list)

['winter squash', 'mexican seasoning', 'mixed spice', 'honey', 'butter', 'olive oil', 'salt']

list

In [20]:
new_df.to_csv('preprocessed.csv',  index=False, header=True)

In [21]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231637 entries, 0 to 231636
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ingredients  231637 non-null  object
 1   calories     231637 non-null  float64
 2   fats         231637 non-null  float64
 3   protein      231637 non-null  float64
 4   carbs        231637 non-null  float64
dtypes: float64(4), object(1)
memory usage: 8.8+ MB

# Dummy Food Choice Data Preprocessing

In [22]:
#Opening food_choice csv file in the raw data folder

foodchoice_path = os.path.join(BASE, 'raw_data', 'foodchoice_dataset.csv')
foodchoice_df =pd.read_csv(foodchoice_path)
foodchoice_df.head(3)

,index,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),...,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct
0,0,1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,...,7.0,51.368,21.021,3.043,215.0,5.0,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0
1,1,1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,...,4.6,45.390,19.874,3.331,225.0,3.8,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0
2,2,1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,...,8.6,61.924,28.732,3.694,256.0,12.8,1 tbsp,205.0,1 cup,0.0

In [23]:
# Drop other columns while keeping the food only
foodchoice_df = foodchoice_df[['Shrt_Desc']]
foodchoice_df.head(3)
foodchoice_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Shrt_Desc  8790 non-null   object
dtypes: object(1)
memory usage: 68.8+ KB

In [24]:
#Save cleaned dummy food choice data as a csv
foodchoice_df.to_csv('foodchoice_dummy.csv', index=False, header=True)